### PR TITLE
Add support for "dependency only" tracking

### PR DESCRIPTION
**Pull request by nikomatsakis**
This is closer to what Glimmer does.

### CODE REVIEW

**Comment by matklad** [comment]
LGTM! We might also add a mix between dependecy-only and memoized storage, which stores Option<V> and allows to gc only the values.

**Comment by nikomatsakis** [comment]
@matklad interesting thought, maybe file an issue? that might also just be how memoized works, full stop?

**Comment by nikomatsakis** [comment]
I wanted to get this merged, anyhow, because I realized that supporting it would require threading a bit more information through (e.g., now we have to return the changed-at information).

**Comment by matklad** [comment]
>that might also just be how memoized works, full stop?

Yep, and also https://github.com/nikomatsakis/salsa/issues/7#issuecomment-425893534. Filing the issue.

**Pull request merged**
